package ca.bcit.comp2522.project.wordGame;

import java.io.IOException;
import java.time.LocalDateTime;
import java.util.Random;
import java.util.Scanner;

/**
 * This class puts together the entire game flow, managing question rounds,
 * processing user input through the command line, determining question types,
 * and handling the end of game score saving and high-score message generation.
 * <p>
 * The core high-score logic (loading, comparison, message generation) is delegated
 * to the {@code Score} class, as required by the assignment guidelines.
 * This class only interacts with the {@code Score} object to save the final result
 * and print the final, formatted high-score message.
 * <p>
 *
 * @author Ibrahim Abudalah
 * @version 1.0
 */
public final class WordGame
{
    private static final int    QUESTIONS_PER_GAME      = 10;
    private static final int    MAX_ATTEMPTS            = 2;
    private static final String SCORE_FILE              = "score.txt";
    private static final String ANSWER_YES              = "yes";
    private static final String ANSWER_NO               = "no";
    private static final int    TYPE_CAPITAL_TO_COUNTRY = 0;
    private static final int    TYPE_COUNTRY_TO_CAPITAL = 1;
    private static final int    TYPE_FACT_TO_COUNTRY    = 2;
    private static final int    NUM_TYPES               = 3;
    private static final int    FIRST_ATTEMPT           = 1;
    private static final int    ZERO_SCORE              = 0;
    private static final Random RANDOM                  = new Random();
    private static       int    lastAttemptUsed         = ZERO_SCORE;

    /**
     * The entry point for the command line game, called by {@code Main.java}.
     * This method initializes the game world, enters the main game loop, and handles
     * the final score, file persistence, and high-score reporting logic.
     *
     * @param scanner the shared {@code Scanner} instance passed from the application's entry point
     * @throws IllegalArgumentException if the provided {@code Scanner} is null
     * @throws IllegalStateException    if the World object fails to load country data
     */
    public static void play(final Scanner scanner) throws IOException
    {

        validateScanner(scanner);
        final World world;
        world = new World();

        int totalGames = ZERO_SCORE;
        int totalFirst = ZERO_SCORE;
        int totalSecond = ZERO_SCORE;
        int totalIncorrect = ZERO_SCORE;

        boolean continuePlaying = true;

        while (continuePlaying)
        {
            final Result result;
            result = playOneGame(scanner, world);

            totalGames += FIRST_ATTEMPT;
            totalFirst += result.firstAttempt;
            totalSecond += result.secondAttempt;
            totalIncorrect += result.incorrect;

            printSessionSummary(result);

            continuePlaying = askPlayAgain(scanner);
        }

        // Final score calculation.
        final Score finalScore;
        finalScore = new Score(
            LocalDateTime.now(),
            totalGames,
            totalFirst,
            totalSecond,
            totalIncorrect
        );


        // Load all previous scores for comparison.
        Score.loadScores(SCORE_FILE);

        // Fetch the highest average score from all loaded records.
        final Score previousHigh;
        previousHigh = Score.getPreviousHighScore();

        // Print the high-score message generated by the Score class.
        System.out.println(finalScore.getHighScoreMessage(previousHigh));

        // Append the new score record to the persistence score file.
        Score.appendScoreToFile(finalScore, SCORE_FILE);
    }

    /**
     * Executes one full game session consisting of {@value QUESTIONS_PER_GAME} questions.
     * This is the main loop that selects countries and question types, and gets the result.
     *
     * @param scanner the shared {@code Scanner} instance for user input
     * @param world   the {@code World} object containing all country data
     * @return a {@code Result} object detailing the performance for this single game
     */
    private static Result playOneGame(final Scanner scanner,
                                      final World world)
    {

        // Local variables accumulate scores for this specific game.
        int firstAttempt = ZERO_SCORE;
        int secondAttempt = ZERO_SCORE;
        int incorrect = ZERO_SCORE;
        int i;

        for (i = ZERO_SCORE; i < QUESTIONS_PER_GAME; i++)
        {
            final Country country;
            country = world.getRandomCountry();

            final int type;
            type = RANDOM.nextInt(NUM_TYPES);

            final boolean correct;
            correct = askQuestion(scanner, country, type);

            if (correct)
            {
                if (lastAttemptUsed == FIRST_ATTEMPT)
                {
                    firstAttempt++;
                }
                else
                {
                    secondAttempt++;
                }
            }
            else
            {
                incorrect++;
            }
        }

        return new Result(firstAttempt, secondAttempt, incorrect);
    }

    /**
     * Selects and executes a question based on the provided type, directing control
     * to the appropriate specialized question handler method.
     *
     * @param scanner the shared {@code Scanner} for input
     * @param country the {@code Country} object that the question is based on
     * @param type    the integer type constant defining the question format
     * @return {@code true} if the answer was correct, {@code false} otherwise
     * @throws IllegalStateException if an unknown question type constant is encountered
     */
    private static boolean askQuestion(final Scanner scanner,
                                       final Country country,
                                       final int type)
    {

        return switch (type)
        {
            case TYPE_CAPITAL_TO_COUNTRY -> askCapitalToCountry(scanner, country);
            case TYPE_COUNTRY_TO_CAPITAL -> askCountryToCapital(scanner, country);
            case TYPE_FACT_TO_COUNTRY -> askFactToCountry(scanner, country);
            default -> throw new IllegalStateException("Unknown question type.");
        };
    }

    /**
     * Presents a question where the player must identify the country given its capital city.
     *
     * @param scanner the shared {@code Scanner} for input.
     * @param country the {@code Country} object containing the answer.
     * @return the boolean result of {@code processAnswer}.
     */
    private static boolean askCapitalToCountry(final Scanner scanner,
                                               final Country country)
    {
        System.out.println("\nWhich country has the capital: " +
                           country.getCapitalCityName());
        return processAnswer(scanner, country.getName());
    }

    /**
     * Presents a question where the player must identify the capital city given the country's name.
     *
     * @param scanner the shared {@code Scanner} for input.
     * @param country the {@code Country} object containing the answer.
     * @return the boolean result of {@code processAnswer}.
     */
    private static boolean askCountryToCapital(final Scanner scanner,
                                               final Country country)
    {
        System.out.println("\nWhat is the capital city of: " +
                           country.getName());
        return processAnswer(scanner, country.getCapitalCityName());
    }

    /**
     * Presents a question where the player must identify the country given a random fact.
     *
     * @param scanner the shared {@code Scanner} for input.
     * @param country the {@code Country} object containing the answer.
     * @return the boolean result of {@code processAnswer}.
     */
    private static boolean askFactToCountry(final Scanner scanner,
                                            final Country country)
    {
        final String[] facts;
        facts = country.getFacts();

        final int index;
        index = RANDOM.nextInt(facts.length);

        System.out.println("\nWhich country does this fact describe?");
        System.out.println("\"" + facts[index] + "\"");

        return processAnswer(scanner, country.getName());
    }

    /**
     * Handles the question answering loop, allowing for up to {@value MAX_ATTEMPTS}.
     * Compares the player's guess against the correct answer.
     * Updates the static {@code lastAttemptUsed} variable upon a correct guess.
     *
     * @param scanner the shared {@code Scanner} for user input.
     * @param correct the correct String answer.
     * @return {@code true} if the player guessed correctly within the maximum attempts; {@code false} otherwise.
     */
    private static boolean processAnswer(final Scanner scanner,
                                         final String correct)
    {
        // Reset the counter before starting attempts.
        lastAttemptUsed = ZERO_SCORE;

        int attempt;
        for (attempt = FIRST_ATTEMPT; attempt <= MAX_ATTEMPTS; attempt++)
        {
            final String prompt;
            prompt = (attempt == FIRST_ATTEMPT) ? "Your answer: " : "Your second attempt: ";

            System.out.print(prompt);

            final String guess;
            guess = scanner.nextLine().trim();

            if (guess.equalsIgnoreCase(correct))
            {
                System.out.println("CORRECT");
                lastAttemptUsed = attempt;
                return true;
            }

            System.out.println("INCORRECT");
        }

        System.out.println("The correct answer was " + correct);
        return false;
    }

    /**
     * Prints a summary of the most recently played game's results to the console.
     *
     * @param r the {@code Result} object containing the single game's stats breakdown.
     */
    private static void printSessionSummary(final Result r)
    {
        System.out.println("\n" + FIRST_ATTEMPT + " word game played");
        System.out.println(r.firstAttempt + " correct answers on the first attempt");
        System.out.println(r.secondAttempt + " correct answers on the second attempt");
        System.out.println(r.incorrect + " incorrect answers on two attempts each");
    }

    /**
     * Prompts the player to see if they wish to play another round. This is a
     * loop that ensures the player provides a valid {@value ANSWER_YES} or {@value ANSWER_NO} input.
     *
     * @param scanner the shared {@code Scanner} for user input
     * @return {@code true} if the player wishes to play again, {@code false} otherwise
     */
    private static boolean askPlayAgain(final Scanner scanner)
    {
        while (true)
        {
            System.out.print("\nPlay again? (Yes/No): ");
            final String input;
            input = scanner.nextLine().trim().toLowerCase();

            if (input.equals(ANSWER_YES))
            {
                return true;
            }
            if (input.equals(ANSWER_NO))
            {
                return false;
            }

            System.out.println("Invalid. Please type Yes or No.");
        }
    }

    /**
     * Validates that the provided {@code Scanner} instance is not null.
     *
     * @param scanner the {@code Scanner} instance to check
     * @throws IllegalArgumentException if the scanner reference is null
     */
    private static void validateScanner(final Scanner scanner)
    {
        if (scanner == null)
        {
            throw new IllegalArgumentException("Scanner cannot be null.");
        }
    }

    /**
     * A private static immutable class used to bundle the results of a single
     * {@code playOneGame} session, facilitating the safe return of multiple score values.
     */
    private static final class Result
    {
        final int firstAttempt;
        final int secondAttempt;
        final int incorrect;

        /**
         * Constructs a {@code Result} object with the stats of a single game.
         *
         * @param firstAttempt  the count of correct answers made on the first try
         * @param secondAttempt the count of correct answers made on the second try
         * @param incorrect     the count of answers missed on both attempts
         */
        Result(final int firstAttempt,
               final int secondAttempt,
               final int incorrect)
        {

            this.firstAttempt  = firstAttempt;
            this.secondAttempt = secondAttempt;
            this.incorrect     = incorrect;
        }
    }
}